dist: xenial
sudo: require

language: cpp

addons:
  apt:
    update: true
    packages:
      - build-essential
      - libboost-all-dev
      - libboost-program-options-dev
      - bison
      - flex
      - python
      - perl
      - zlib1g-dev
      - python-minimal
      - ninja-build
      - wget
      - curl
      - unionfs-fuse
      - git
      - doxygen
      - graphviz
      - python3
      - python3-pip
      - subversion
      - libgmp-dev
      - libmpfr-dev
      - libncurses5-dev
      - libncursesw5-dev

before_script:
  - git config --global user.email "map2check@domain.com"
  - git config --global user.name "Map2Check"
  - mkdir build
  - cd build
  - wget http://releases.llvm.org/6.0.0/clang+llvm-6.0.0-x86_64-linux-gnu-ubuntu-16.04.tar.xz
  - tar xf clang+llvm-6.0.0-x86_64-linux-gnu-ubuntu-16.04.tar.xz
  - mv clang+llvm-6.0.0-x86_64-linux-gnu-ubuntu-16.04 clang
  - export LLVM_DIR=`pwd`/clang/lib/cmake/llvm
  - export CXX=$LLVM_DIR/../../../bin/clang++
  - export CC=$LLVM_DIR/../../../bin/clang
  - cmake .. -G Ninja -DENABLE_TEST=ON -DLLVM_DIR=$LLVM_DIR -DCMAKE_INSTALL_PREFIX=../release/

script: ninja && ninja install && ctest

after_script:
  - cd ../release
  - cp -r $LLVM_DIR_BASE/lib/clang/$LLVM_VERSION/include/* ./include
  - cp -r $LLVM_DIR_BASE/lib/clang ./lib
  - cp /usr/bin/ld ./bin/
  - cp /usr/lib/x86_64-linux-gnu/libbfd-2.26.1-system.so ./lib
  - cp /usr/lib/gcc/x86_64-linux-gnu/5/libstdc++.a ./lib/
  - cd ..
  - tar czf map2check.tar.gz release

notifications:
  email:
    recipients:
      - herberthb12@gmail.com
      - rafa.sa.xp@gmail.com
    on_success: never # default: change
    on_failure: never # default: always
