language: cpp
compiler: clang
dist: trusty
#sudo: require

addons:
  apt:
    packages: libboost-all-dev cmake make

#before_install:
#  - sudo apt-get install -qq cmake make

script:
  - mkdir build
  - cd build
  - cmake ..
  - make

notifications:
  email:
    recipients:
      - rafa.sa.xp@gmail.com 
    on_success: never # default: change
    on_failure: never # default: always
