sudo: required

language: cpp

services:
  - docker

before_install:
  - docker build -t hrocha/mapdevel .
#  - docker run -it --name=mapdevel -v $(pwd):/home/map2check/devel_tool/mygitclone:Z hrocha/mapdevel /bin/bash

# command to run tests
#script:
#  - ./release/map2check -h

notifications:
  email:
    recipients:
      - herberthb12@gmail.com      
    on_success: never # default: change
    on_failure: always # default: always
