sudo: required

language: cpp

services:
  - docker

before_install:
  - docker build -t hrocha/mapdevel .
  - docker run --name=mapdevel -v hrocha/mapdevel /bin/bash -c "./release/map2check -h"

# command to run tests
script:
  - docker ps -a | grep -q mapdevel

notifications:
  email:
    recipients:
      - herberthb12@gmail.com      
    on_success: never # default: change
    on_failure: always # default: always
