dist: xenial
sudo: require

language: cpp

addons:
  apt:
    update: true
    packages:
      - build-essential
      - libboost-all-dev
      - libboost-program-options-dev
      - clang-3.8
      - llvm-3.8
      - llvm-3.8-dev
      - bison
      - flex
      - python
      - perl
      - zlib1g-dev 
      - python-minimal
      - ninja-build
      - wget
      - curl
      - unionfs-fuse
      - git
      - doxygen
      - graphviz
      - python3
      - python3-pip
      - subversion
      - libgmp-dev
      - libmpfr-dev
      - libncurses5-dev
      - libncursesw5-dev

before_script:
  - git config --global user.email "map2check@domain.com"
  - git config --global user.name "Map2Check"
  - mkdir build
  - cd build
  - cmake .. -G Ninja -DCMAKE_INSTALL_PREFIX=../release/

script: ninja && ninja install

notifications:
  email:
    recipients:
      - herberthb12@gmail.com
      - rafa.sa.xp@gmail.com 
    on_success: never # default: change
    on_failure: never # default: always
