sudo: required

language: cpp

services:
  - docker

before_install:
  - docker build -t hrocha/mapdevel .
  - docker run --name=mapdevel -v $(pwd):/home/map2check/devel_tool/mygitclone:Z hrocha/mapdevel /bin/bash -c "ls; cd /home/map2check/devel_tool/mygitclone; ./build-map2check.sh; ./release/map2check -h"

# command to run tests
script:
  - docker ps -a | grep -q mapdevel

#group: stable
#dist: precise

notifications:
  email:
    recipients:
      - herberthb12@gmail.com
      - rafa.sa.xp@gmail.com 
    on_success: never # default: change
    on_failure: always # default: always
