dist: xenial
sudo: require

language: cpp

services: 
  - docker

before_script:
  - docker build -t hrocha/mapdevel --no-cache -f Dockerfile .

script: 
  - docker run --rm -v $(pwd):/home/map2check/devel_tool/mygitclone:Z hrocha/mapdevel /bin/bash -c "cd /home/map2check/devel_tool/mygitclone; ./make-release.sh"

notifications:
  email:
    recipients:
      - herberthb12@gmail.com
      - rafa.sa.xp@gmail.com
    on_success: never # default: change
    on_failure: never # default: always
