dist: xenial
sudo: require

language: cpp

addons:
  apt:
    update: true
    
before_install:
  - sudo apt-get install -y build-essential \
    libboost-all-dev \
    libboost-program-options-dev \
    clang-3.8 llvm-3.8 llvm-3.8-dev \
    bison flex python perl zlib1g-dev \
    python-minimal \
    cmake \
    ninja-build \
    wget \
    curl \
    unionfs-fuse \
    vim \
    git \
    doxygen \
    graphviz \
    python3 \
    python3-pip \
    subversion \
    libgmp-dev \
    libmpfr-dev \   
    libncurses5-dev \
    libncursesw5-dev

before_script:
  - mkdir build
  - cd build
  - cmake .. -G Ninja -DCMAKE_INSTALL_PREFIX=../release/

script: ninja && ninja install

notifications:
  email:
    recipients:
      - herberthb12@gmail.com
      - rafa.sa.xp@gmail.com 
    on_success: never # default: change
    on_failure: never # default: always
