sudo: required

language: cpp

services:
  - docker

before_install:
  - docker build -t hrocha/mapdevel .
  - docker run --name=mapdevel hrocha/mapdevel /bin/bash -c "cd /home/map2check/devel_tool/map_src_on_docker; ./release/map2check -h"

# command to run tests
script:
  - docker ps -a | grep -q mapdevel

notifications:
  email:
    recipients:
      - rafa.sa.xp@gmail.com      
    on_success: always # default: change
    on_failure: always # default: always
