sudo: required

language: cpp

services:
  - docker

before_install:
  - docker build -t hrocha/mapdevel .
  - docker run hrocha/mapdevel /bin/sh -c "./map_src_on_docker/build/map2check -v"

# command to run tests
#script:
#  - bundle exec rake test

notifications:
  email:
    recipients:
      - herberthb12@gmail.com      
    on_success: never # default: change
    on_failure: always # default: always
