dist: ubuntu1604
#sudo: require

addons:
  apt:
    packages: libboost-all-dev cmake make llvm-6.0-dev clang-6.0 build-essential curl

#before_install:
#  - sudo apt-get install -qq cmake make

script:
  - ./make-release

notifications:
  email:
    recipients:
      - rafa.sa.xp@gmail.com 
    on_success: never # default: change
    on_failure: never # default: always
